# 1) create and populate your .env file from template.env
# 2) run 'yarn imp-deploy' to deploy webapp and database to local docker compose
# a simple docker-compose / docker-stack file to setup a MariaDB instance and an nginx server
version: '3.8'
services:
# web server to host the web application
 webapp:
  image: nginx:${IMPNGINXVERSION}
  volumes:
   - ${PWD}/build:/usr/share/nginx/html
# your Docker host must expose port ${IMPFRONTENDPORT} from your .env file
# if you want to expose the front end to the internet
  ports:
   - "${IMPFRONTENDPORT}:80"

# backend MariaDB database
 database:
  image: mariadb:${IMPMARIADBVERSION}
  volumes:
   - ${PWD}/mariadbdata:/var/lib/mysql
  environment:
   - MYSQL_ROOT_USER="${IMPROOTUSERNAME}"
   - MYSQL_ROOT_PASSWORD="${IMPROOTPASSWORD}"
   - MYSQL_USER="${IMPUSERNAME}"
   - MYSQL_PASSWORD="${IMPPASSWORD}"
   - MYSQL_DATABASE="${IMPDATABASE}"
  ports:
   - '${IMPEXTERNALPORT}:${IMPCONTAINERPORT}'
# your Docker host must expose port ${IMPEXTERNALPORT} from your .env file
# if you want to use a IMP instance hosted outside your local network
  networks:
   - impnet
networks:
 impnet:
  external: false
