# 1) populate a .env file made from template.env
# 2) open your desired firewall ports at your docker host:
## ${REACT_APP_WEB_PORT} exposes the front end web client to the internet
# 3) run 'npm run docker:up' to deploy frontend and database with docker compose
version: '3.9'
services:
# nginx web server to host the web application
 frontend:
  image: nginx:alpine
#   build: src-ui
#   image: imp_interface:alpine
  volumes:
   - $PWD/build:/usr/share/nginx/html:ro
  ports:
   - $REACT_APP_WEB_PORT:80
  networks:
   - react

networks:
 react:
  external: false
  driver: bridge
