# 1) create and populate a .env file made from template.env
# 2) point your desired firewall ports at your docker host:
## ${REACT_APP_APIPORT} exposes the api to the internet
## ${REACT_APP_FRONTENDPORT} exposes the front end web client to the internet
# 3) run 'yarn imp-up' to deploy webapp and database with docker compose
version: '3.9'
services:
# nginx web server to host the web application
 webapp:
  image: nginx:${REACT_APP_NGINXVERSION}
  volumes:
   - ${PWD}/build:/usr/share/nginx/html
  ports:
   - "${REACT_APP_FRONTENDPORT}:80"
  networks:
   - react

# MariaDB database to host the backend data
 database:
  image: mariadb:${REACT_APP_MARIADBVERSION}
  volumes:
   - ${PWD}/mariadbdata:/var/lib/mysql
  environment:
   - MYSQL_ROOT_USER="${REACT_APP_ROOTUSER}"
   - MYSQL_ROOT_PASSWORD="${REACT_APP_ROOTPASSWORD}"
   - MYSQL_USER="${REACT_APP_USER}"
   - MYSQL_PASSWORD="${REACT_APP_PASSWORD}"
   - MYSQL_DATABASE="${REACT_APP_DATABASENAME}"
  networks:
   - maria
  expose:
   - 3306

# api server to connect webapp to database
 api:
  build: src-api
  depends_on:
   - database
   - webapp
  networks:
   - maria
   - react
  ports:
   - ${REACT_APP_APIPORT}:${REACT_APP_APIPORT}
   
networks:
 react:
  external: false
 maria:
  external: false
