## a simple docker-compose file to setup a MariaDB instance
version: '3.8'
services:
 mariadb:
  image: mariadb:${IMPMARIADBVERSION}
  volumes:
# 1) make a directory to store your database files with this command: 
## mkdir mariadb
  environment:
   - ${PWD}/mariadb:/var/lib/mysql
   - MYSQL_ROOT_USER="${IMPROOTUSERNAME}"
   - MYSQL_ROOT_PASSWORD="${IMPROOTPASSWORD}"
   - MYSQL_USER="${IMPUSERNAME}"
   - MYSQL_PASSWORD="${IMPPASSWORD}"
   - MYSQL_DATABASE="${IMPDATABASE}"
  ports:
   - '${IMPEXTERNALPORT}:${IMPCONTAINERPORT}'
# 2) populate your .env file from template.env
# your Docker host must expose port ${IMPEXTERNALPORT}
# (assuming you want to use IMP from outside your local network)
# 3) then deploy your database with this command:
## docker stack deploy -f --service-ports mariadb-stack.yml ${STACKNAME}
  networks:
   - mariadb
networks:
 mariadb:
  external: false
