/** @format */
/**
 * Module 6.5
 * an array of product types to be used in mocked products
 */
export const nouns: string[] = [
  `Ascot`,
  `Boomerang`,
  `Cherry`,
  `Date`,
  `Eggplant`,
  `Flyswatter`,
  `Grape`,
  `Honeydew`,
  `Igloo`,
  `Jalapeno`,
  `Kiwi`,
  `Lemon`,
  `Mango`,
  `Nectarine`,
  `Outhouse`,
  `Papaya`,
  `Quince`,
  `Raspberry`,
  `Strawberry`,
  `Tangerine`,
  `Umbrella`,
  `Watermelon`,
  `Zucchini`,
  `Television`,
  `Computer`,
  `Smartphone`,
  `Laptop`,
  `Tablet`,
  `Smart Watch`,
  `Shears`,
  `Hair Dryer`,
  `Toothbrush`,
  `Robot`,
  `Shirt`,
  `Pants`,
  `Shoes`,
  `Hat`,
  `Socks`,
  `Gloves`,
  `Jacket`,
  `Sweater`,
  `T-Shirt`,
  `Hoodie`,
  `Jumper`,
  `Sweatshirt`,
  `Chair`,
  `Couch`,
  `Bed`,
  `Microwave`,
  `Toaster`,
  `Refrigerator`,
  `Oven`,
  `Air Fryer`,
  `Stereo`,
  `Speaker`,
  `Headphones`,
  `Radio`,
  `Drill`,
  `Saw`,
  `Screwdriver`,
  `Wrench`,
  `Hammer`,
  `Pliers`,
  `Router`,
  `Socket`,
  `Crate`,
  `Bag`,
  `Box`,
  `Bucket`,
  `Bottle`,
  `Can`,
  `Carton`,
  `Jar`,
  `Jug`,
  `Pail`,
  `Pillow`,
  `Sack`,
  `Tote Bag`,
  `Tray`,
  `Vase`,
  `Bowl`,
  `Doormat`,
  `Carpet`,
  `Toilet Brush`,
  `Printer`,
  `Home Gym`,
  `Recliner`,
  `Dog Bed`,
  `Dresser`,
  `Armoire`,
  `Bookshelf`,
  `Coat Hooks`,
  `Mirror`,
  `Spatula`,
  `Whisk`,
  `Wok`,
  `Zamboni`,
  `Belt`,
  `Tie Rack`,
  `Towel Bar`,
  `Washcloth`,
  `Bathtub`,
  `Shower Head`,
  `Picture Frame`,
  `Microprocessor`,
  `Grand Piano`,
  `Escalator`,
  `Neon Sign`,
  `Floor Lamp`,
  `Particle Accelerator`,
  `Satellite Dish`,
  `Remote Control`,
  `Postal Scale`,
  `Adhesive Remover`,
  `A/C Tray`,
  `CAT5 Crimper`,
  `Faucet Handle`,
  `Aglet Set`,
  `VESA Mount`,
  `Pressure Gauge`,
  `Wiper Blades`,
  `Nozzle`,
  `Handle`,
  `Cable Ties`,
  `Mop Bucket`,
  `Edge Mill`,
  `Gromit`,
  `Label Maker`,
  `Door Hinge Pin`,
  `Blinker Bulb`,
  `Non-fungible Token`,
  `Plank`,
  `Floor Tile`,
  `Paint Roller`,
  `Dermal Punch`,
  `Baking Rack`,
  `Googly Eyes`,
  `Lariat`,
  `Plumbus`,
  `Eyepatch`,
  `Grogu Figure`,
  `Sock Patch`,
  `Salad Spinner`,
  `Zebra Pelt`,
  `Fish Scaler`,
  `Gold Coin`,
  `Silver Coin`,
  `Bronze Coin`,
  `Copper Coin`,
  `Platinum Coin`,
  `Plague Doctor Mask`
]
